"""Butterfly ParameterSchema (Pack Spec §4.3)."""

from __future__ import annotations

from typing import Any


def get_schema() -> dict[str, Any]:
    return {
        "common": [
            {
                "name": "direction",
                "type": "enum",
                "label": "Direction (single / BWB only)",
                "required": False,
                "options": ["call", "put"],
                "description": "Which side for single-fly or BWB. Batman always uses both call and put flies.",
            },
            {
                "name": "dte_type",
                "type": "enum",
                "label": "DTE Type",
                "required": True,
                "options": ["0dte", "1dte", "2_5_dte", "custom"],
            },
            {
                "name": "dte_min",
                "type": "number",
                "label": "Min DTE",
                "required": False,
                "min": 0,
                "max": 10,
                "dependsOn": ["dte_type=custom"],
            },
            {
                "name": "dte_max",
                "type": "number",
                "label": "Max DTE",
                "required": False,
                "min": 0,
                "max": 10,
                "dependsOn": ["dte_type=custom"],
            },
            {
                "name": "max_capital_at_risk",
                "type": "number",
                "label": "Max Capital at Risk",
                "required": True,
                "min": 0.01,
            },
            {
                "name": "max_capital_unit",
                "type": "enum",
                "label": "Capital Unit",
                "required": True,
                "options": ["dollars", "percent_of_capital"],
                "default": "dollars",
            },
            {
                "name": "primary_metric",
                "type": "enum",
                "label": "Primary Optimization Metric",
                "required": True,
                "options": ["sharpe", "sortino", "calmar", "return_avg_dd"],
            },
            {
                "name": "entry_conditions",
                "type": "json",
                "label": "Entry Conditions",
                "required": False,
            },
            {
                "name": "exit_rules",
                "type": "json",
                "label": "Exit Rules",
                "required": True,
                "description": "Must include dynamic trailing based on premium decay rate",
            },
            {
                "name": "butterfly_family",
                "type": "enum",
                "label": "Butterfly Family",
                "required": True,
                "options": ["batman", "single", "broken_wing"],
                "description": (
                    "Batman = call fly + put fly package (each wing-symmetric). "
                    "Single = one call or put fly. Broken wing = BWB."
                ),
            },
            {
                "name": "underlying",
                "type": "string",
                "label": "Underlying",
                "required": False,
                "default": "SPX",
            },
        ],
        "variants": {
            "batman": [
                {
                    "name": "symmetric_regime",
                    "type": "enum",
                    "label": "Regime",
                    "required": True,
                    "options": ["high_vix", "mid_vix", "low_vix", "campaign"],
                },
                {
                    "name": "width_style",
                    "type": "enum",
                    "label": "Width Style (scan)",
                    "required": True,
                    "options": ["wide", "variable", "narrow", "fixed_30_50"],
                },
                {
                    "name": "width_points_min",
                    "type": "number",
                    "label": "Min Width (points)",
                    "required": False,
                    "min": 10,
                    "max": 100,
                },
                {
                    "name": "width_points_max",
                    "type": "number",
                    "label": "Max Width (points)",
                    "required": False,
                    "min": 10,
                    "max": 100,
                },
                {
                    "name": "match_side_widths",
                    "type": "boolean",
                    "label": "Match call & put widths",
                    "required": False,
                    "default": True,
                    "description": (
                        "When true (usual Batman), call fly and put fly share the same width. "
                        "When false, set call_width_points and put_width_points separately."
                    ),
                },
                {
                    "name": "call_width_points",
                    "type": "number",
                    "label": "Call fly width (points)",
                    "required": False,
                    "min": 5,
                    "max": 150,
                    "dependsOn": ["match_side_widths=false"],
                    "description": "Width of the call-side symmetric fly only",
                },
                {
                    "name": "put_width_points",
                    "type": "number",
                    "label": "Put fly width (points)",
                    "required": False,
                    "min": 5,
                    "max": 150,
                    "dependsOn": ["match_side_widths=false"],
                    "description": "Width of the put-side symmetric fly only",
                },
                {
                    "name": "debit_to_width_min",
                    "type": "number",
                    "label": "Min Debit-to-Width",
                    "required": True,
                    "min": 0.01,
                    "max": 0.15,
                    "description": "Uses total package debit / (call_width + put_width)",
                },
                {
                    "name": "debit_to_width_max",
                    "type": "number",
                    "label": "Max Debit-to-Width",
                    "required": True,
                    "min": 0.01,
                    "max": 0.15,
                },
                {
                    "name": "directional_bias",
                    "type": "enum",
                    "label": "Directional Bias",
                    "required": False,
                    "options": ["none", "with_trend"],
                    "dependsOn": ["symmetric_regime=mid_vix"],
                },
                {
                    "name": "timing",
                    "type": "enum",
                    "label": "Timing",
                    "required": False,
                    "options": ["morning", "before_close", "any"],
                },
                {
                    "name": "frequency_per_week",
                    "type": "number",
                    "label": "Target Frequency per Week",
                    "required": False,
                    "min": 1,
                    "max": 5,
                    "dependsOn": ["symmetric_regime=campaign"],
                },
                {
                    "name": "vix_1d_mode",
                    "type": "enum",
                    "label": "1-Day VIX Adjustment",
                    "required": False,
                    "options": ["auto", "manual"],
                    "default": "auto",
                },
            ],
            "single": [
                {
                    "name": "symmetric_regime",
                    "type": "enum",
                    "label": "Regime",
                    "required": False,
                    "options": ["high_vix", "mid_vix", "low_vix", "campaign"],
                },
                {
                    "name": "width_style",
                    "type": "enum",
                    "label": "Width Style",
                    "required": True,
                    "options": ["wide", "variable", "narrow", "fixed_30_50"],
                },
                {
                    "name": "width_points_min",
                    "type": "number",
                    "label": "Min Width (points)",
                    "required": False,
                    "min": 10,
                    "max": 100,
                },
                {
                    "name": "width_points_max",
                    "type": "number",
                    "label": "Max Width (points)",
                    "required": False,
                    "min": 10,
                    "max": 100,
                },
                {
                    "name": "debit_to_width_min",
                    "type": "number",
                    "label": "Min Debit-to-Width",
                    "required": True,
                    "min": 0.01,
                    "max": 0.15,
                },
                {
                    "name": "debit_to_width_max",
                    "type": "number",
                    "label": "Max Debit-to-Width",
                    "required": True,
                    "min": 0.01,
                    "max": 0.15,
                },
                {
                    "name": "timing",
                    "type": "enum",
                    "label": "Timing",
                    "required": False,
                    "options": ["morning", "before_close", "any"],
                },
            ],
            "broken_wing": [
                {
                    "name": "bwb_style",
                    "type": "enum",
                    "label": "BWB Style",
                    "required": True,
                    "options": [
                        "A_efficiency",
                        "A_plus_scalp",
                        "B_steep",
                        "B_plus_gamma",
                    ],
                },
                {
                    "name": "broken_wing_side",
                    "type": "enum",
                    "label": "Broken Wing Side",
                    "required": True,
                    "options": ["upper", "lower"],
                },
                {
                    "name": "target_debit_to_payoff_min",
                    "type": "number",
                    "label": "Min Debit-to-Payoff",
                    "required": True,
                    "min": 0.01,
                    "max": 1.0,
                },
                {
                    "name": "target_debit_to_payoff_max",
                    "type": "number",
                    "label": "Max Debit-to-Payoff",
                    "required": True,
                    "min": 0.01,
                    "max": 1.0,
                },
                {
                    "name": "min_convexity_quality",
                    "type": "enum",
                    "label": "Minimum Convexity Quality",
                    "required": False,
                    "options": ["medium", "high", "extreme"],
                    "description": "Optional until convexity calibration (Q1); scores are provisional",
                },
                {
                    "name": "positioning_notes",
                    "type": "string",
                    "label": "Positioning Notes",
                    "required": False,
                },
            ],
        },
        "validationRules": [
            "max_capital_at_risk must be > 0",
            "primary_metric must be risk-adjusted",
            "exit_rules must include dynamic premium decay trailing",
            "No undefined risk structures allowed",
            "Batman = call fly + put fly; each fly is wing-symmetric",
            "Batman widths usually matched; match_side_widths=false allows per-side width",
            "Debit-to-width uses package debit / total width for Batman",
            "Broken Wing requires bwb_style and broken_wing_side",
            "min_convexity_quality is optional until calibration",
        ],
    }
